port to syn 2.0
Compiling pin-init fails with this error:

error[E0432]: unresolved imports `syn::visit_mut`, `syn::visit_mut`
 --> pin-init-internal/src/pin_init.rs:4:29
  |
4 |     punctuated::Punctuated, visit_mut, visit_mut::VisitMut, Attribute, Data, DeriveInput, Error,
  |                             ^^^^^^^^^  ^^^^^^^^^ could not find `visit_mut` in `syn`
  |                             |
  |                             no `visit_mut` in the root

The easiest way to fix it is to use syn 2.0, which requires a few changes.